[[news]]
date = "2026.05"
content = "One paper accepted by MICCAI-26 (Early Accepted)."

[[news]]
date = "2025.11"
content = "I am selected to join the first Young Editorial Board of EngMedicine."

[[news]]
date = "2025.11"
content = "One paper accepted by AAAI-26 (Oral)."

[[news]]
date = "2025.10"
content = "One paper accepted by IEEE BIBM-25 (Oral)."

[[news]]
date = "2025.07"
content = "I start my work as a specially appointed associate researcher and postdoc at IAI, Hefei Comprehensive National Science Center."

[[news]]
date = "2025.05"
content = "The moment I've been working toward for years — I just aced my Ph.D. defense!"

[[news]]
date = "2025.04"
content = "One paper accepted by npj Digital Medicine."

[[news]]
date = "2025.03"
content = "One paper accepted by MIDL-25 (Oral)."

[[news]]
date = "2025.01"
content = "One paper accepted by Medical Image Analysis."

[[news]]
date = "2024.10"
content = "One paper accepted by npj Digital Medicine."

[[news]]
date = "2024.09"
content = "One paper accepted by NeurIPS-24."

[[news]]
date = "2024.05"
content = "One paper accepted by MICCAI-24 (Early Accepted)."

[[news]]
date = "2024.02"
content = "One paper accepted by MIDL-24 (Oral)."

[[news]]
date = "2024.02"
content = "One paper accepted by MIDL-24."

[[news]]
date = "2023.05"
content = "One paper accepted by MICCAI-23."
