type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "安徽省优秀毕业生"
subtitle = "安徽省"
date = "2025"
content = ""

[[items]]
title = "中国科学技术大学优秀毕业生"
subtitle = "中国科学技术大学"
date = "2025"
content = ""

[[items]]
title = "学术一等奖学金"
subtitle = "中国科学技术大学"
date = "2021, 2023, 2024"
content = ""

[[items]]
title = "学术二等奖学金"
subtitle = "中国科学技术大学"
date = "2022"
content = ""

[[items]]
title = "苏州工业园奖学金"
subtitle = "苏州工业园"
date = "2021"
content = ""
