[[news]]
date = "2026.05"
content = "一篇论文被 MICCAI-26 接收 (Early Accepted)。"

[[news]]
date = "2025.11"
content = "入选 EngMedicine 首届青年编委会。"

[[news]]
date = "2025.11"
content = "一篇论文被 AAAI-26 接收 (Oral)。"

[[news]]
date = "2025.10"
content = "一篇论文被 IEEE BIBM-25 接收 (Oral)。"

[[news]]
date = "2025.07"
content = "开始在合肥综合性国家科学中心人工智能研究院担任特任副研究员/博士后。"

[[news]]
date = "2025.05"
content = "顺利完成博士答辩！"

[[news]]
date = "2025.04"
content = "一篇论文被 npj Digital Medicine 接收。"

[[news]]
date = "2025.03"
content = "一篇论文被 MIDL-25 接收 (Oral)。"

[[news]]
date = "2025.01"
content = "一篇论文被 Medical Image Analysis 接收。"

[[news]]
date = "2024.10"
content = "一篇论文被 npj Digital Medicine 接收。"

[[news]]
date = "2024.09"
content = "一篇论文被 NeurIPS-24 接收。"

[[news]]
date = "2024.05"
content = "一篇论文被 MICCAI-24 接收 (Early Accepted)。"

[[news]]
date = "2024.02"
content = "一篇论文被 MIDL-24 接收 (Oral)。"

[[news]]
date = "2024.02"
content = "一篇论文被 MIDL-24 接收。"

[[news]]
date = "2023.05"
content = "一篇论文被 MICCAI-23 接收。"
