name: Get Citation Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          pip install -r google_scholar_crawler/requirements.txt
      - name: Run Crawler & Push to google-scholar-stats
        env:
          GOOGLE_SCHOLAR_ID: TxjqAY0AAAAJ
        run: |
          cd google_scholar_crawler
          python main.py
          cd results
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.json
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force